#! /bin/tcsh -f

# This the main NetMHCIIpan 4.1 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	April 2021
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCIIpan 4.1 directory (mandatory)
setenv	NMHOME	/c/Users/Colby/Documents/GitHub/Ghana_CSP_Haplotypes/netMHCII_tool/netMHCIIpan-4.1

# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR /c/tmp/
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCIIpan $NMHOME
setenv NetMHCIIpanPLAT $NMHOME/$PLATFORM
setenv NetMHCIIpanWWWPATH /services/NetMHCIIpan-4.1/tmp
setenv NetMHCIIpanWWWDIR /usr/opt/www/pub/CBS/services/NetMHCIIpan-4.1/tmp


# main ========================================================================
if ( -x $NETMHCIIpan/NetMHCIIpan-4.1.pl ) then
   $NETMHCIIpan/NetMHCIIpan-4.1.pl $*
else
   echo $NETMHCIIpan/NetMHCIIpan-4.1.pl not found
endif

# end of script ===============================================================
